"""Cinema Sound: AI voiceover + procedurally-generated ambience, muxed onto
generated video with ffmpeg — the 'pure sound and voice' finish.

Pipeline (each stage degrades gracefully, never fails the generation):
1. Narration — the director model writes a voiceover sized to the clip's
   duration (~2.2 words/sec reads naturally); the user can override it.
2. Voice — OpenAI-compatible TTS renders the narration (voice selectable).
3. Mix — ffmpeg loudness-normalizes the voice (EBU R128, -16 LUFS) and blends
   it under/over a quiet procedural ambient pad (two detuned sines + tremolo,
   generated by ffmpeg itself — zero assets, zero licensing) plus any original
   audio the provider clip carries (ducked).
4. Serve — the muxed MP4 lands in MEDIA_DIR and is served from
   GET /media/files/{name}; a janitor purges files older than MEDIA_TTL_HOURS.

If ffmpeg or TTS is unavailable the route falls back to the provider's
original URL with an explanatory note — the user always gets a video.
"""

import asyncio
import logging
import os
import re
import shutil
import time
import uuid
from dataclasses import dataclass

import httpx

from ..config import settings
from .llm import llm

log = logging.getLogger(__name__)

# Voices accepted from the client (OpenAI-compatible TTS).
NARRATION_VOICES = {"alloy", "ash", "ballad", "coral", "echo", "fable", "onyx", "nova", "sage", "shimmer", "verse"}

WORDS_PER_SECOND = 2.2          # natural narration pace
TTS_HARD_CAP_WORDS = 120        # keeps TTS snappy even for 15s clips
MEDIA_NAME_RE = re.compile(r"^[a-f0-9]{32}\.mp4$")


@dataclass
class SoundtrackResult:
    filename: str          # served name in MEDIA_DIR
    script: str            # the narration actually spoken
    voice: str
    mode: str              # "voice" | "voice+ambience"


def estimate_word_budget(seconds: int) -> int:
    return max(10, min(int(seconds * WORDS_PER_SECOND), TTS_HARD_CAP_WORDS))


def fit_words(text: str, budget: int) -> str:
    """Clamp narration to the word budget, ending on a sentence boundary if possible."""
    words = text.split()
    if len(words) <= budget:
        return text.strip()
    clipped = " ".join(words[:budget])
    # Prefer ending at a sentence boundary, as long as it keeps a meaningful
    # share of the budget (avoids degenerate one-word voiceovers).
    last_end = None
    for m in re.finditer(r"[.!?](?:\s|$)", clipped):
        last_end = m.start() + 1
    if last_end is not None:
        kept = len(clipped[:last_end].split())
        if kept >= max(4, budget // 2):
            clipped = clipped[:last_end]
    return clipped.strip().rstrip(",;:—-") + ("" if clipped.strip().endswith((".", "!", "?")) else ".")


NARRATION_PROMPT = """You are the voiceover writer for a premium AI film studio.
Write a voiceover of AT MOST {budget} words for a {seconds}s video about the user's idea.
Tone: cinematic, warm, confident — movie-trailer grade but never cheesy.
Plain prose, 1-3 short sentences, present tense where natural.
No stage directions, no sound-effect cues, no quotes, no preamble."""


async def write_narration(prompt: str, seconds: int) -> str:
    """Director-model voiceover sized to the clip; trims the raw idea on any failure."""
    budget = estimate_word_budget(seconds)
    try:
        text = await llm.complete(
            [
                {"role": "system", "content": NARRATION_PROMPT.format(budget=budget, seconds=seconds)},
                {"role": "user", "content": prompt.strip()},
            ],
            temperature=0.7,
            max_tokens=220,
        )
        text = text.strip().strip('"').strip()
        if text:
            return fit_words(text, budget)
    except Exception as e:  # LLM down → narrate the user's own words
        log.warning("narration writer unavailable (%s) — falling back to prompt narration", e)
    return fit_words(prompt.strip(), budget)


def ffmpeg_path() -> str | None:
    """Resolve the ffmpeg binary, honoring an explicit path first."""
    configured = (settings.FFMPEG_PATH or "").strip()
    if configured and configured != "ffmpeg":
        return configured if os.path.exists(configured) else None
    return shutil.which("ffmpeg")


async def _run(cmd: list[str], timeout: int = 180) -> tuple[int, str]:
    proc = await asyncio.create_subprocess_exec(
        *cmd, stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.PIPE
    )
    try:
        _, err = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    except asyncio.TimeoutError:
        proc.kill()
        await proc.wait()
        return -1, "timeout"
    return proc.returncode or 0, (err or b"").decode(errors="replace")[-400:]


def build_mux_cmd(
    ffbin: str, video_in: str, voice_in: str, out: str, seconds: int, *, with_bed: bool, with_original: bool
) -> list[str]:
    """Pure argv builder — unit-tested so the live pipeline never ships a broken filtergraph."""
    d = max(1, int(seconds))
    fade_out_at = max(d - 1.5, 0)
    if not with_bed and not with_original:
        mix = "[1:a]loudnorm=I=-16:TP=-1.5:LRA=11[aout]"
        return [
            ffbin, "-y", "-i", video_in, "-i", voice_in,
            "-filter_complex", mix, "-map", "0:v", "-map", "[aout]",
            "-c:v", "copy", "-c:a", "aac", "-b:a", "160k",
            "-movflags", "+faststart", "-shortest", out,
        ]
    parts = [f"[1:a]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur={d}[vo]"]
    if with_original:
        parts.append("[0:a]volume=0.35[orig]")
    if with_bed:
        parts.append(
            f"sine=frequency=108:duration={d},volume=0.7[s1];"
            f"sine=frequency=162:duration={d}[s2];"
            f"[s1][s2]amix=inputs=2:normalize=0,volume=0.08,tremolo=f=0.12:d=0.6,"
            f"afade=t=in:st=0:d=1.5,afade=t=out:st={fade_out_at}:d=1.5[bed]"
        )
    sources = ["[vo]"] + (["[orig]"] if with_original else []) + (["[bed]"] if with_bed else [])
    parts.append(f"{''.join(sources)}amix=inputs={len(sources)}:duration=first:normalize=0[aout]")
    cmd = [ffbin, "-y", "-i", video_in, "-i", voice_in]
    return cmd + [
        "-filter_complex", ";".join(parts), "-map", "0:v", "-map", "[aout]",
        "-c:v", "copy", "-c:a", "aac", "-b:a", "160k",
        "-movflags", "+faststart", "-t", str(d), out,
    ]


async def _probe_streams(ffbin: str, video_in: str) -> bool:
    """True when the provider clip carries its own audio stream (kept, ducked, in the mix)."""
    probe = shutil.which("ffprobe") or (
        os.path.join(os.path.dirname(ffbin), "ffprobe") if os.path.dirname(ffbin) else "ffprobe"
    )
    proc = await asyncio.create_subprocess_exec(
        probe, "-v", "error", "-select_streams", "a:0", "-show_entries", "stream=codec_type",
        "-of", "csv=p=0", video_in,
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL,
    )
    try:
        out, _ = await asyncio.wait_for(proc.communicate(), timeout=30)
    except asyncio.TimeoutError:
        proc.kill()
        await proc.wait()
        return False
    return proc.returncode == 0 and bool((out or b"").strip())


def _janitor(media_dir: str) -> None:
    """Purge muxed files older than MEDIA_TTL_HOURS (best effort)."""
    try:
        cutoff = time.time() - settings.MEDIA_TTL_HOURS * 3600
        for name in os.listdir(media_dir):
            if not MEDIA_NAME_RE.match(name):
                continue
            path = os.path.join(media_dir, name)
            if os.path.getmtime(path) < cutoff:
                os.remove(path)
    except OSError:
        pass


async def add_soundtrack(
    video_url: str,
    *,
    seconds: int,
    voice_name: str = "alloy",
    narration: str | None = None,
    prompt: str = "",
    with_bed: bool = True,
) -> SoundtrackResult | None:
    """Full pipeline. Returns None when ffmpeg is missing; lets TTS/auth errors bubble up."""
    ffbin = ffmpeg_path()
    if not ffbin:
        log.warning("ffmpeg not found — video delivered without soundtrack")
        return None
    voice_id = voice_name if voice_name in NARRATION_VOICES else "alloy"
    script = (narration or "").strip() or await write_narration(prompt, seconds)

    from .voice import voice as voice_svc  # local import: keeps voice seam lazy

    speech = await voice_svc.synthesize(script, voice_id)

    os.makedirs(settings.MEDIA_DIR, exist_ok=True)
    work = f"/tmp/mood-mux-{uuid.uuid4().hex}"
    os.makedirs(work, exist_ok=True)
    video_in = os.path.join(work, "in.mp4")
    voice_in = os.path.join(work, "voice.mp3")
    try:
        # 1) Pull the provider clip (size-capped)
        cap = settings.VIDEO_MAX_DOWNLOAD_MB * 1024 * 1024
        async with httpx.AsyncClient(timeout=httpx.Timeout(30.0, read=120.0)) as http:
            async with http.stream("GET", video_url) as r:
                r.raise_for_status()
                written = 0
                with open(video_in, "wb") as fh:
                    async for chunk in r.aiter_bytes(1 << 16):
                        written += len(chunk)
                        if written > cap:
                            raise ValueError("provider clip exceeds download cap")
                        fh.write(chunk)
        with open(voice_in, "wb") as fh:
            fh.write(speech)

        # 2) Mix: full (voice + ducked original + ambience) → voice-only fallback
        with_original = await _probe_streams(ffbin, video_in)
        name = f"{uuid.uuid4().hex}.mp4"
        final = os.path.join(settings.MEDIA_DIR, name)
        cmd = build_mux_cmd(ffbin, video_in, voice_in, final, seconds, with_bed=with_bed, with_original=with_original)
        code, err = await _run(cmd)
        mode = "voice+ambience" if with_bed else "voice"
        if code != 0:
            log.warning("full audio mix failed (%s) — retrying voice-only", err)
            cmd = build_mux_cmd(ffbin, video_in, voice_in, final, seconds, with_bed=False, with_original=False)
            code, err = await _run(cmd)
            mode = "voice"
        if code != 0:
            log.warning("voice-only mix failed too: %s", err)
            return None

        _janitor(settings.MEDIA_DIR)
        return SoundtrackResult(filename=name, script=script, voice=voice_id, mode=mode)
    finally:
        shutil.rmtree(work, ignore_errors=True)
